export const inicio = () => {
  const inicioDiv = document.createElement('div');
  inicioDiv.id = 'inicioDiv';
  const marca = document.createElement('h1');
  marca.className = 'marca';
  marca.textContent = '¡Bienvenida a Transmuta!';
  const slogan = document.createElement('h3');
  slogan.textContent = '"Transformando las emociones en poder"';
  slogan.id = 'slogan';
  const imagenInicioDeSesion = document.createElement('img');
  imagenInicioDeSesion.id = 'imagenInicioDeSesion';
  imagenInicioDeSesion.src = '/lib/componentes/Assets/mounstruo.png';
  inicioDiv.append(marca);
  inicioDiv.append(slogan);
  inicioDiv.append(imagenInicioDeSesion);
  const divInicioDeSesion = document.createElement('div');
  divInicioDeSesion.id = 'divInicioDeSesion';
  const inicioSesion = document.createElement('h2');
  inicioSesion.textContent = 'Iniciar Sesion';
  inicioSesion.id = 'inicio-sesion';
  const correoElectronico = document.createElement('input');
  correoElectronico.textContent = 'Ingrese aqui su correo';
  correoElectronico.id = 'correo-electronico';
  const contraseña = document.createElement('input');
  contraseña.textContent = 'Ingrese aqui su contraseña';
  contraseña.id = 'contraseña';
  const botonIngresar = document.createElement('button');
  botonIngresar.textContent = 'Ingresar';
  botonIngresar.id = 'boton-ingresar';
  const opcion = document.createElement('h5');
  opcion.textContent = 'o';
  opcion.className = 'letra-o';
  const textoSinCuenta = document.createElement('h5');
  textoSinCuenta.textContent = 'No te haz registrado aun. Registrate aqui';
  textoSinCuenta.className = 'texto-no-cuenta';
  const registro = document.createElement('h5');
  registro.textContent = 'Aqui';
  registro.className = 'registro';
  divInicioDeSesion.appendChild(inicioSesion);
  divInicioDeSesion.appendChild(correoElectronico);
  divInicioDeSesion.appendChild(contraseña);
  divInicioDeSesion.appendChild(botonIngresar);
  divInicioDeSesion.appendChild(opcion);
  divInicioDeSesion.appendChild(textoSinCuenta);
  divInicioDeSesion.appendChild(registro);
  inicioDiv.append(divInicioDeSesion);

  return inicioDiv;
};
